import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display} from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";
const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-serif'
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'flex min-h-screen flex-col font-serif antialiased',
          geistSans.variable,
          playfair.variable
        )}
      >
        <Providers>
          <Header />
          <main className='grow pt-24'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
